/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pag103n6;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author raffaele.lubrano
 */
public class autoibus extends javax.swing.JFrame {

    /**
     * Creates new form autoibus
     */
    public autoibus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Gigi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("scuolabus");
        jLabel1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jButton1.setText("genera autobus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("genera camion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1)
                        .addGap(417, 417, 417)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Graphics O1=jPanel1.getGraphics(); 
        
        Color gialloscuro = new Color(255, 204, 0);
        Color azzurro = new Color(51, 153, 255);
        
        //carrozzeria
        O1.translate(100,100);
        O1.setColor(gialloscuro);
        O1.fillRect(100,100,200,100);
        
        //ruota posteriore
        O1.setColor(Color.BLACK);
        O1.translate(100,100);
        O1.fillOval(25,95,25,25);
        
        //ruota anteriore
        O1.setColor(Color.BLACK);
        O1.fillOval(150,95,25,25);
        
        //finestra 1
        O1.setColor(azzurro);
        O1.fillRect(25,25,25,25);
        
        //finestra 2
        O1.setColor(azzurro);
        O1.fillRect(55,25,25,25);
        
        //finestra 3
        O1.setColor(azzurro);
        O1.fillRect(85,25,25,25);
        
        //finestra 4
        O1.setColor(azzurro);
        O1.fillRect(115,25,25,25);
        
        //porta
        O1.setColor(azzurro);
        O1.fillRect(145,25,25,50);
        
        //vetro anteriore
        O1.setColor(azzurro);
        O1.fillRect(195,5,5,60);
        
        //asta porta
        O1.setColor(Color.BLACK);
        O1.fillRect(150,25,5,50);
        
        //scarico
        O1.translate(100,100);
        O1.setColor(Color.BLACK);
        O1.fillRect(-100,-110,10,15);
        
        //fumo 1
        O1.setColor(Color.GRAY);
        O1.fillOval(-120,-125,15,15);
        
        //fumo 2
        O1.setColor(Color.GRAY);
        O1.fillOval(-135,-140,15,15);
        
        //fumo 3
        O1.setColor(Color.GRAY);
        O1.fillOval(-150,-155,15,15);
        
        //fumo 4
        O1.setColor(Color.GRAY);
        O1.fillOval(-165,-170,15,15);
        
        //sole
        O1.setColor(Color.YELLOW);
        O1.fillOval(65,-170,25,25);
        jLabel1.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Graphics C =  jPanel2.getGraphics();
       
        //C.translate(300, 200);
        //carico
        C.drawRect(0, 0, 350, 250);
        C.setColor(Color.yellow);
        C.fillRect(1, 1, 349, 249);
       
        //appoggio
        C.setColor(Color.black);
        C.drawRect(0, 250, 550, 50);
        C.setColor(Color.magenta);
        C.fillRect(1, 251, 549, 49);
       
        //testaCamion
        C.setColor(Color.black);
        C.drawRect(400, 50, 150, 200);
        C.setColor(Color.magenta);
        C.fillRect(401, 51, 149, 199);
       
        //finestrino
        C.setColor(Color.black);
        C.drawRect(500, 70, 50, 80);
        C.setColor(Color.blue);
        C.fillRect(501, 71, 49, 79);
       
        //ruote
        C.setColor(Color.black);
        C.fillOval(50, 270, 70, 70);
        C.setColor(Color.orange);
        C.fillOval(60, 280, 50, 50);
       
        C.setColor(Color.black);
        C.fillOval(150, 270, 70, 70);
        C.setColor(Color.orange);
        C.fillOval(160, 280, 50, 50);
       
        C.setColor(Color.black);
        C.fillOval(450, 270, 70, 70);
        C.setColor(Color.orange);
        C.fillOval(460, 280, 50, 50);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autoibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autoibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autoibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autoibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autoibus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
